spring.application.name=mailAdmin
# DB接続情報 (あなたの環境に合わせて書き換えてください)
spring.datasource.url=jdbc:postgresql://localhost:5432/maildb
spring.datasource.username=mailuser
spring.datasource.password=p@ssw0rD
spring.datasource.driver-class-name=org.postgresql.Driver

# JPAの設定 (既存DBを使うため、自動でテーブル構造を変えないようにします)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true